services:
  - type: web
    name: tapdel
    env: node
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: APP_URL
        value: https://tapdel.onrender.com
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 