services:
  - type: web
    name: tapdel
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    staticPublishPath: ./dist
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: VITE_TELEGRAM_BOT_TOKEN
        sync: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 